apiVersion: v1
kind: Pod
metadata:
  # La creaci칩n del objeto se realizar치 en el namespace especificado
  namespace: espeisbox
  name: caja
  labels:
    # Configuraci칩n de las etiquetas solicitadas
    name: caja
    version: "0.1"
spec:
  containers:
  - name: caja
    image: busybox
    # Para poder dejar la imagen de busybox arrancada se configura
    # que en el arranque se ejecute el comando sleep que hace una pausa
    # y configuramos esa pausa para que dure 3600 segundos
    command:
      - sleep
      - "3600"
    # Definici칩n de la variable de entorno
    env:
    - name: miVar
      value: "Estoy dentro"