apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: tamaño_del_volumen
  accessModes:
    - Tipo_de_acceso
  hostPath:
    path: Path_del_host