apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - Tipo_de_acceso
  resources:
    requests:
      storage: tamaño_del_claim